; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

	TITLE	C:\Users\b30640\laboper\Demo5\SysCore\Kernel\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Ogtpy
; File c:\users\b30640\laboper\demo5\syscore\kernel\main.cpp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 9    : 
; 10   : 
; 11   : }

	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
END
